version: '3.7'
services:
  web:
    build: ./docker/web
    ports:
      - '3000:3000'
    volumes:
      - ./:/app:cached
      - "bundle:/usr/local/bundle"
    tty: true
    depends_on:
      - db
      - redis
  db:
    image: postgres:12.1-alpine
    volumes:
      - ./docker/db/storage:/var/lib/postgresql/data:cached
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --locale=ja_JP.UTF-8' # (3)
      TZ: Asia/Tokyo
  redis:
    image: "redis:latest"
    volumes:
      - "./docker/redis:/data:cached"
volumes:
  bundle: